<?php
namespace Azera\Boot;

final class BootstrapResolver
{
    /** Name of the generated discovery cache file inside vendor/. */
    private const DISCOVERY_CACHE_FILENAME = 'azera-bootstrap.php';

    public static function resolve(string $projectRoot): ?BootstrapProvider
    {
        // 1. CLI override
        $argv          = $_SERVER['argv'] ?? [];
        $saveRequested = in_array('--save', $argv, true);
        foreach ($argv as $arg) {
            if (str_starts_with($arg, '--provider=')) {
                $fqcn = substr($arg, 10);
                if (class_exists($fqcn)) {
                    if ($saveRequested) {
                        BootstrapDiscovery::saveProvider($projectRoot, $fqcn);
                    }
                    return new $fqcn();
                }
            }
            if (str_starts_with($arg, '--bootstrap=')) {
                $file = $projectRoot . '/' . substr($arg, 12);
                if (is_file($file)) {
                    $callable = require $file;
                    if ($saveRequested) {
                        // For file-based bootstraps we can't persist a FQCN,
                        // so we skip caching. The --save flag is primarily
                        // for --provider=.
                    }
                    return new FileBridge($callable);
                }
            }
        }

        // 2. composer.json extra
        $composer = $projectRoot . '/composer.json';
        if (is_file($composer)) {
            $json  = json_decode(file_get_contents($composer), true);
            $extra = $json['extra']['azera'] ?? [];
            if (!empty($extra['provider']) && class_exists($extra['provider'])) {
                return new $extra['provider']();
            }
            if (!empty($extra['bootstrap']) && is_file($projectRoot . '/' . $extra['bootstrap'])) {
                $callable = require $projectRoot . '/' . $extra['bootstrap'];
                return new FileBridge($callable);
            }
        }

        // 3. Root azera-boot.php (file form)
        $azeraPhp = $projectRoot . '/azera-boot.php';
        if (is_file($azeraPhp)) {
            $callable = require $azeraPhp;
            if (!is_callable($callable)) {
                throw new \RuntimeException("azera-boot.php must return a callable.");
            }
            return new FileBridge($callable);
        }

        // 4. Discovery cache generated by BootstrapDiscovery composer plugin.
        //    This file is written during `composer install` / `dump-autoload`
        //    and contains the FQCN of a discovered BootstrapProvider implementor.
        $discoveryCache = $projectRoot . '/vendor/' . self::DISCOVERY_CACHE_FILENAME;
        if (is_file($discoveryCache)) {
            $cached = require $discoveryCache;
            if (is_array($cached) && !empty($cached['provider']) && class_exists($cached['provider'])) {
                $fqcn = $cached['provider'];
                if (in_array(BootstrapProvider::class, class_implements($fqcn), true)) {
                    return new $fqcn();
                }
            }
        }

        // 5. Fallback: any already-loaded class implementing BootstrapProvider.
        //    This only fires if the discovery cache is missing AND a provider
        //    happens to already be loaded (e.g. via a custom entry point).
        foreach (get_declared_classes() as $class) {
            if (in_array(BootstrapProvider::class, class_implements($class), true)) {
                if ($class === FileBridge::class) {
                    continue; // skip the internal FileBridge class
                }
                return new $class();
            }
        }

        return null;
    }
}

final class FileBridge implements BootstrapProvider
{
    public function __construct(private $callable) {}
    public function boot(): void
    {
        ($this->callable)();
    }
}